### ISSUE TITLE
Jerky Stripes

### ISSUE THREAD

**Issue by Levrden** [keijiro/Krbv#1]
Hi !
I have used you project and edited it to achieve new effects. But i don't understand how to smooth the stripes "moving".
As you can see the white ones 
![root3](https://user-images.githubusercontent.com/24231978/94993178-62bdcc00-058f-11eb-888c-48622e2c17b5.gif)

move in a very jerky way...
Of course, if i speed them up, it is smooth but i would like to have them slow
Do you have an idea on which parameter to edit ?

Thanks !

**Comment by keijiro** [comment]
Maybe you should use "over time" rather than "over distance" in the Event Trigger Rate blocks: https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@7.1/manual/Events.html
